# Generated by Django 5.0.1 on 2024-02-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_train_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='arrival_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='departure_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
