# Generated by Django 5.0.1 on 2024-02-09 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.PositiveIntegerField()),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='train.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='train.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.train')),
            ],
        ),
    ]
