# Generated by Django 5.0.1 on 2024-03-24 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='STS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zone', models.IntegerField()),
                ('Ward', models.IntegerField()),
                ('Address', models.CharField(max_length=255)),
                ('Capacity', models.IntegerField()),
                ('Latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('STS_Manager_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
