# Generated by Django 5.0.1 on 2024-03-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Inactive', 'Inactive'), ('Under Maintenance', 'Under Maintenance'), ('In Transit', 'In Transit')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(choices=[(1, '1 ton'), (2, '2 ton'), (3, '3 ton'), (4, '4 ton'), (5, '5 ton'), (6, '6 ton'), (7, '7 ton'), (8, '8 ton'), (9, '9 ton'), (10, '10 ton')]),
        ),
    ]
