# Generated by Django 5.0.1 on 2024-03-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(choices=[(3, '3 ton'), (5, '5 ton'), (7, '7 ton')]),
        ),
    ]
