# Generated by Django 5.0.1 on 2024-03-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_wastetransfer_arrival_cost_wastetransfer_return_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteTransferQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('landfill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.landfill')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.path')),
                ('sts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.sts')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.vehicle')),
            ],
        ),
    ]
