# Generated by Django 5.0.1 on 2024-03-25 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_alter_vehicle_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landfill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255)),
                ('Capacity', models.IntegerField()),
                ('Latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Landfill_Manager_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WasteTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departure', models.DateTimeField(null=True)),
                ('arrival', models.DateTimeField(null=True)),
                ('sts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.sts')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.vehicle')),
            ],
        ),
    ]
