# Generated by Django 5.0.1 on 2024-03-26 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0004_vehicle_loaded_fuel_cost_per_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landfill',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='sts',
            name='manager',
        ),
        migrations.AddField(
            model_name='landfill',
            name='managers',
            field=models.ManyToManyField(related_name='landfill_managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sts',
            name='managers',
            field=models.ManyToManyField(related_name='sts_managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
