# Generated by Django 5.0.1 on 2024-03-26 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0005_remove_landfill_manager_remove_sts_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landfill',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='sts',
            name='managers',
        ),
        migrations.CreateModel(
            name='LandfillManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landfill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.landfill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='STSManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.sts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
