# Generated by Django 5.0.1 on 2024-03-26 10:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0006_remove_landfill_managers_remove_sts_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='landfillmanager',
            unique_together={('user',)},
        ),
        migrations.AlterUniqueTogether(
            name='stsmanager',
            unique_together={('user',)},
        ),
    ]
