AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  munmudtest

  Sample SAM Template for munmudtest

Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  RouteCalculator:
    Type: AWS::Location::RouteCalculator
    Properties:
      DataSource: Esri
      CalculatorName:
        Fn::Sub: ${AWS::StackName}-routecalculator
  RouteCalculatorLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: route_calculator/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Environment:
        Variables:
          ROUTE_CALCULATOR:
            Ref: RouteCalculator
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - geo:CalculateRoute
              Resource:
                - Fn::GetAtt: [RouteCalculator, CalculatorArn]
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: "*"
      Events:
        RouteEvents:
          Type: Api
          Properties:
            Path: /route
            Method: post

Outputs:
  RouteApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/route/"
